<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="AUTOMATION" duration-ms="7126" started-at="2015-12-24T13:11:47Z" finished-at="2015-12-24T13:11:54Z">
    <groups>
    </groups>
    <test name="fftest" duration-ms="7126" started-at="2015-12-24T13:11:47Z" finished-at="2015-12-24T13:11:54Z">
      <class name="commonLibrary.SampleTestNG">
        <test-method status="FAIL" signature="BeforeTest()[pri:0, instance:commonLibrary.SampleTestNG@4cdbe50f]" name="BeforeTest" is-config="true" duration-ms="0" started-at="2015-12-24T13:11:47Z" finished-at="2015-12-24T13:11:47Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at commonLibrary.SetUp_TearDown.setup(SetUp_TearDown.java:95)
	at commonLibrary.SampleTestNG.BeforeTest(SampleTestNG.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:551)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
        </test-method> <!-- BeforeTest -->
        <test-method status="SKIP" signature="AtTest()[pri:0, instance:commonLibrary.SampleTestNG@4cdbe50f]" name="AtTest" duration-ms="3" started-at="2015-12-24T13:11:54Z" finished-at="2015-12-24T13:11:54Z">
        </test-method> <!-- AtTest -->
      </class> <!-- commonLibrary.SampleTestNG -->
    </test> <!-- fftest -->
  </suite> <!-- AUTOMATION -->
</testng-results>
